apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns01-prod-clusterissuer
spec:
  acme:
    email: acme@surdej.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: kubasurdej@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
