---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-prod-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: acme@surdej.me
    privateKeySecretRef:
      name: http01-prod-clusterissuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-staging-clusterissuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: acme@surdej.me
    privateKeySecretRef:
      name: http01-staging-clusterissuer-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
