apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
  targetNamespace: argocd-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kuskoman/personal-infrstructure.git
    targetRevision: HEAD
    path: helm/argocd-apps
    helm:
      releaseName: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-apps
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 25
