{{- with .Values.argoingress -}}
{{- if .enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/managed-by: Helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    meta.helm.sh/release-namespace: argocd
    {{- if .whitelist.enabled }}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .whitelist.sourceRanges }}
    {{- end }}
spec:
  rules:
  - host: {{ .host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              name: https
  {{ if .tls.enabled -}}
  tls:
  - hosts:
    - {{ .host }}
    secretName: {{ default "argocd-tls" .tls.secretName }}
  {{- end -}}

{{- end -}}{{- end -}}
