apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  targetNamespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: argocd-ingress
spec:
  project: default
  source:
    repoURL: https://github.com/kuskoman/personal-infrastructure.git
    targetRevision: HEAD
    path: helm/argocd-ingress
    helm:
      releaseName: argocd-ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
