apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  targetNamespace: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.4.2
    helm:
      values: |
        controller:
          config:
            use-proxy-protocol: "true"

          service:
            externalTrafficPolicy: "Local"
            annotations:
              # https://www.digitalocean.com/docs/kubernetes/how-to/configure-load-balancers/
              # https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/annotations.md
              service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
