apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  targetNamespace: hashicorp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: vault
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.23.0
  destination:
    server: https://kubernetes.default.svc
    namespace: hashicorp
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
