apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hashicorp-certificate
  namespace: hashicorp
spec:
  secretName: hashicorp-tls
  issuerRef:
    name: dns01-prod-clusterissuer
    kind: "ClusterIssuer"
    group: "cert-manager.io"
  dnsNames:
    - vault.surdej.me
